//get all favorites
//get  http://localhost:3001/favorites/

//delete favorites
//delete  http://localhost:3001/favorites/2

//add favorites
//post  http://localhost:3001/favorites/1223

//search superhero by name:
get  http://localhost:3001/superheros/capt?page=69